language: node_js
node_js:
  - "16"

install:
  - npm install

script:
  - npm run build

deploy:
  provider: netlify
  skip_cleanup: true
  site_id: YOUR_NETLIFY_SITE_ID
  auth_token: YOUR_NETLIFY_AUTH_TOKEN
  dir: dist
  on:
    branch: main