language: node_js
node_js:
  - "16"

install:
  - npm install

script:
  - npm run build

deploy:
  provider: vercel
  skip_cleanup: true
  api_token: YOUR_VERCEL_TOKEN
  dir: dist
  on:
    branch: main